In [1]:
import pandas as pd
import numpy as np
import json

In [3]:
# read sample csv and skip label rows
CK118 = pd.read_csv("/Users/luoronghui/Desktop/GSE218000_RAW/GSM6732253_GA09805_DBEC_MolsPerCell.csv.gz", skiprows=6)
CK119 = pd.read_csv("/Users/luoronghui/Desktop/GSE218000_RAW/GSM6732254_GA09931_DBEC_MolsPerCell.csv.gz", skiprows=6)
CK254 = pd.read_csv("/Users/luoronghui/Desktop/GSE218000_RAW/GSM6732260_GA42710_DBEC_MolsPerCell.csv.gz", skiprows=6)
CK258 = pd.read_csv("/Users/luoronghui/Desktop/GSE218000_RAW/GSM6732263_GA43652_DBEC_MolsPerCell.csv.gz", skiprows=6)

UC133_2 = pd.read_csv("/Users/luoronghui/Desktop/GSE218000_RAW/GSM6732255_GA10148_DBEC_MolsPerCell.csv.gz", skiprows=6)
UC141 = pd.read_csv("/Users/luoronghui/Desktop/GSE218000_RAW/GSM6732258_GA11986_DBEC_MolsPerCell.csv.gz", skiprows=6)
UC287 = pd.read_csv("/Users/luoronghui/Desktop/GSE218000_RAW/GSM6732261_GA42739_DBEC_MolsPerCell.csv.gz", skiprows=6)
UC309 = pd.read_csv("/Users/luoronghui/Desktop/GSE218000_RAW/GSM6732264_GA43821_DBEC_MolsPerCell.csv.gz", skiprows=6)

In [15]:
# observe the format
UC133_2.head()

,Cell_Index,CD103|ITGAE|AHS0001|pAbO,CD127|IL7R|AHS0028|pAbO,CD161:DX12|KLRB1|AHS0002|pAbO,CD195:2D7|CCR5|AHS0070|pAbO,CD197|CCR7|AHS0007|pAbO,CD27:M-T271|CD27|AHS0025|pAbO,CD3:SK7|CD3E|AHS0033|pAbO,CD45RA:HI100|PTPRC|AHS0009|pAbO,CD45RO|PTPRC|AHS0036|pAbO,...,VPREB3|NM_013378.2|Reference_end,VPS28|NM_016208.3|Reference_end,VSIG4|NM_007268.2|Reference_end,XBP1|NM_005080.3|Reference_end,XCL1|NM_002995.2|Reference_end,YBX3|NM_003651.4|Reference_end,ZAP70|NM_001079.3|Reference_end,ZBED2|NM_024508.4|Reference_end,ZBTB16|NM_006006.4|Reference_end,ZNF683|NM_173574.3|Reference_end
0,842256,9,44,11,9,16,216,512,124,32,...,0,0,0,47,0,1,0,0,0,0
1,799991,6,42,26,7,19,545,661,80,33,...,0,1,0,90,0,5,0,0,0,0
2,49504,6,37,7,3,11,408,309,92,14,...,0,1,0,57,0,1,0,0,0,0
3,529256,10,34,8,3,8,128,439,91,19,...,0,0,0,11,0,0,0,0,0,0
4,55281,12,42,8,5,27,224,398,130,23,...,0,0,0,31,0,1,0,0,0,0

In [13]:
# observe the shape
UC133_2.shape

(6477, 433)

In [17]:
UC141.shape

(7000, 433)

In [19]:
UC287.shape

(8124, 433)

In [21]:
UC309.shape

(10973, 433)

In [23]:
# stack CK
CK118.insert(0, "Sample", "CK118")
CK119.insert(0, "Sample", "CK119")
CK254.insert(0, "Sample", "CK254")
CK258.insert(0, "Sample", "CK258")
CK = pd.concat([CK118, CK119, CK254, CK258])
CK.insert(0, "Condition", "Control_samples")

UC133_2.insert(0, "Sample", "UC133_2")
UC141.insert(0, "Sample", "UC141")
UC287.insert(0, "Sample", "UC287")
UC309.insert(0, "Sample", "UC309")
UC = pd.concat([UC133_2, UC141, UC287, UC309])
UC.insert(0, "Condition", "Ulcerative_colitis")
combined = pd.concat([CK, UC])

/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  CK118.insert(0, "Sample", "CK118")
/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  CK119.insert(0, "Sample", "CK119")
/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  CK254.insert(0, "Sample", "CK254")
/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  CK258.insert(0, "Sample", "CK258")
/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  CK.insert(0, "Condition", "Control_samples")
/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  UC133_2.insert(0, "Sample", "UC133_2")
/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  UC141.insert(0, "Sample", "UC141")
/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  UC287.insert(0, "Sample", "UC287")
/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  UC309.insert(0, "Sample", "UC309")
/var/folders/dy/8nydh7kj1p9493mfydk0p1nr0000gn/T/ipykernel_47176/95513222.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  UC.insert(0, "Condition", "Ulcerative_colitis")

In [25]:
# check the shape of the UC-CK combined file
combined.shape

(57745, 435)

In [33]:
combined

,Condition,Sample,Cell_Index,CD103|ITGAE|AHS0001|pAbO,CD127|IL7R|AHS0028|pAbO,CD161:DX12|KLRB1|AHS0002|pAbO,CD195:2D7|CCR5|AHS0070|pAbO,CD197|CCR7|AHS0007|pAbO,CD27:M-T271|CD27|AHS0025|pAbO,CD3:SK7|CD3E|AHS0033|pAbO,...,VPREB3|NM_013378.2|Reference_end,VPS28|NM_016208.3|Reference_end,VSIG4|NM_007268.2|Reference_end,XBP1|NM_005080.3|Reference_end,XCL1|NM_002995.2|Reference_end,YBX3|NM_003651.4|Reference_end,ZAP70|NM_001079.3|Reference_end,ZBED2|NM_024508.4|Reference_end,ZBTB16|NM_006006.4|Reference_end,ZNF683|NM_173574.3|Reference_end
0,Control_samples,CK118,707743,12,23,4,23,12,34,37,...,0,2,0,30,0,0,0,0,0,0
1,Control_samples,CK118,577396,12,21,11,14,16,2710,290,...,2,0,0,30,0,0,0,0,0,0
2,Control_samples,CK118,89979,17,18,6,21,7,463,30,...,0,1,0,18,0,3,0,0,0,0
3,Control_samples,CK118,57379,13,11,5,16,5,11,32,...,0,0,0,34,0,0,0,0,0,0
4,Control_samples,CK118,658439,6,17,4,3,5,2031,51,...,1,2,0,30,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10968,Ulcerative_colitis,UC309,763956,1,15,1,2,0,93,42,...,0,0,0,0,0,0,0,0,0,0
10969,Ulcerative_colitis,UC309,679358,0,13,0,1,2,122,77,...,0,0,0,0,0,0,0,0,0,0
10970,Ulcerative_colitis,UC309,247020,0,12,11,2,3,106,47,...,0,0,0,0,0,0,0,0,0,0
10971,Ulcerative_colitis,UC309,256030,0,8,1,3,3,35,16,...,0,0,0,0,0,1,0,0,0,0
10972,Ulcerative_colitis,UC309,39492,1,5,1,1,6,9,3,...,0,0,0,0,0,0,0,0,0,0

In [31]:
# check N/A
combined.isna().sum().sum()

np.int64(0)

In [37]:
CD = pd.read_csv("/Users/luoronghui/Desktop/CD_dataframe.csv")

In [39]:
CD

,Condition,Sample,Cell_Index,CD103|ITGAE|AHS0001|pAbO,CD127|IL7R|AHS0028|pAbO,CD161:DX12|KLRB1|AHS0002|pAbO,CD195:2D7|CCR5|AHS0070|pAbO,CD197|CCR7|AHS0007|pAbO,CD27:M-T271|CD27|AHS0025|pAbO,CD3:SK7|CD3E|AHS0033|pAbO,...,VPREB3|NM_013378.2|Reference_end,VPS28|NM_016208.3|Reference_end,VSIG4|NM_007268.2|Reference_end,XBP1|NM_005080.3|Reference_end,XCL1|NM_002995.2|Reference_end,YBX3|NM_003651.4|Reference_end,ZAP70|NM_001079.3|Reference_end,ZBED2|NM_024508.4|Reference_end,ZBTB16|NM_006006.4|Reference_end,ZNF683|NM_173574.3|Reference_end
0,Chrons_Disease,CD134-2,574286,42,38,25,5,34,346,178,...,0,1,0,111,0,0,0,0,0,0
1,Chrons_Disease,CD134-2,612047,63,31,22,15,33,131,198,...,1,2,0,18,0,0,0,0,0,0
2,Chrons_Disease,CD134-2,771787,31,16,20,5,10,2108,103,...,0,0,0,25,0,0,0,0,0,0
3,Chrons_Disease,CD134-2,379330,24,31,22,6,22,408,126,...,0,0,0,33,0,0,0,0,0,0
4,Chrons_Disease,CD134-2,583269,25,15,19,4,16,142,101,...,0,0,0,23,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27774,Chrons_Disease,CD303,72516,4,28,2,6,2,247,57,...,0,0,0,0,0,0,0,0,0,0
27775,Chrons_Disease,CD303,526362,9,2,30,5,5,21,113,...,0,0,0,0,0,0,0,0,0,0
27776,Chrons_Disease,CD303,677963,8,15,16,9,13,15,18,...,0,0,0,0,0,0,0,0,0,0
27777,Chrons_Disease,CD303,458065,224,144,30,79,43,65,257,...,0,0,0,0,0,0,1,0,0,0
27778,Chrons_Disease,CD303,454805,3,85,28,15,6,13,51,...,0,0,0,0,0,0,1,0,0,0

In [27]:
# concatenate UC-CK and C
final = pd.concat([combined, CD])

In [29]:
final.shape

(85524, 435)

In [31]:
final.head()

,Condition,Sample,Cell_Index,CD103|ITGAE|AHS0001|pAbO,CD127|IL7R|AHS0028|pAbO,CD161:DX12|KLRB1|AHS0002|pAbO,CD195:2D7|CCR5|AHS0070|pAbO,CD197|CCR7|AHS0007|pAbO,CD27:M-T271|CD27|AHS0025|pAbO,CD3:SK7|CD3E|AHS0033|pAbO,...,VPREB3|NM_013378.2|Reference_end,VPS28|NM_016208.3|Reference_end,VSIG4|NM_007268.2|Reference_end,XBP1|NM_005080.3|Reference_end,XCL1|NM_002995.2|Reference_end,YBX3|NM_003651.4|Reference_end,ZAP70|NM_001079.3|Reference_end,ZBED2|NM_024508.4|Reference_end,ZBTB16|NM_006006.4|Reference_end,ZNF683|NM_173574.3|Reference_end
0,Control_samples,CK118,707743,12,23,4,23,12,34,37,...,0,2,0,30,0,0,0,0,0,0
1,Control_samples,CK118,577396,12,21,11,14,16,2710,290,...,2,0,0,30,0,0,0,0,0,0
2,Control_samples,CK118,89979,17,18,6,21,7,463,30,...,0,1,0,18,0,3,0,0,0,0
3,Control_samples,CK118,57379,13,11,5,16,5,11,32,...,0,0,0,34,0,0,0,0,0,0
4,Control_samples,CK118,658439,6,17,4,3,5,2031,51,...,1,2,0,30,0,0,0,0,0,0

In [33]:
final

,Condition,Sample,Cell_Index,CD103|ITGAE|AHS0001|pAbO,CD127|IL7R|AHS0028|pAbO,CD161:DX12|KLRB1|AHS0002|pAbO,CD195:2D7|CCR5|AHS0070|pAbO,CD197|CCR7|AHS0007|pAbO,CD27:M-T271|CD27|AHS0025|pAbO,CD3:SK7|CD3E|AHS0033|pAbO,...,VPREB3|NM_013378.2|Reference_end,VPS28|NM_016208.3|Reference_end,VSIG4|NM_007268.2|Reference_end,XBP1|NM_005080.3|Reference_end,XCL1|NM_002995.2|Reference_end,YBX3|NM_003651.4|Reference_end,ZAP70|NM_001079.3|Reference_end,ZBED2|NM_024508.4|Reference_end,ZBTB16|NM_006006.4|Reference_end,ZNF683|NM_173574.3|Reference_end
0,Control_samples,CK118,707743,12,23,4,23,12,34,37,...,0,2,0,30,0,0,0,0,0,0
1,Control_samples,CK118,577396,12,21,11,14,16,2710,290,...,2,0,0,30,0,0,0,0,0,0
2,Control_samples,CK118,89979,17,18,6,21,7,463,30,...,0,1,0,18,0,3,0,0,0,0
3,Control_samples,CK118,57379,13,11,5,16,5,11,32,...,0,0,0,34,0,0,0,0,0,0
4,Control_samples,CK118,658439,6,17,4,3,5,2031,51,...,1,2,0,30,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27774,Chrons_Disease,CD303,72516,4,28,2,6,2,247,57,...,0,0,0,0,0,0,0,0,0,0
27775,Chrons_Disease,CD303,526362,9,2,30,5,5,21,113,...,0,0,0,0,0,0,0,0,0,0
27776,Chrons_Disease,CD303,677963,8,15,16,9,13,15,18,...,0,0,0,0,0,0,0,0,0,0
27777,Chrons_Disease,CD303,458065,224,144,30,79,43,65,257,...,0,0,0,0,0,0,1,0,0,0
27778,Chrons_Disease,CD303,454805,3,85,28,15,6,13,51,...,0,0,0,0,0,0,1,0,0,0

In [35]:
final.to_csv("UC_CK_CD.csv")